name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (locked)
        run: |
          pip install --upgrade pip
          pip install -r requirements.lock

      - name: Lint with flake8
        run: flake8 src tests

      - name: Run pytest suite
        run: pytest --maxfail=1 --disable-warnings -q
